### ISSUE TITLE
On mobile code examples goes "out of bounds".

### ISSUE THREAD

**Issue by NitroNils** [BryceVandegrift/website#1]
In the Firefoxes and Safari on iOS code examples don't fit in their boxes. Many pages have a side ways scrolling option in such cases. If you care?

![image](https://github.com/BryceVandegrift/website/assets/28693786/9a7a271c-584f-4f63-be6f-620c2fe26608)
[here](https://brycevandegrift.xyz/blog/stop-saying-c-and-c++/)

Randomly found your site and enjoyed exploring it. Especially when I saw references to *BSD, troff, Jami, Zig...

**Comment by BryceVandegrift** [comment]
Thanks for pointing that out. I was going to fix that at one point, but I forgot.

**Comment by BryceVandegrift** [comment]
Ok, it has been fixed.
